### ISSUE TITLE
Enable cloudkit schema for prod

### ISSUE THREAD

**Issue by kamaal222** [kamaal111/PocketSlate#2]
# User Feedback

# Reported log

label: Skypiea
type: error
message: failed to subscribe to CloudPhrase iCloud subscription; description='Error saving record subscription with id 49ECB217-56A0-4075-B448-B8EAE9EDD684 to server: Did not find record type: CloudPhrase'; error='<CKError 0x281dc29a0: "Unknown Item" (11/2003); server message = "Did not find record type: CloudPhrase"; op = 744771BF4DADFF0C; uuid = 9A7DB98A-9136-4C01-B420-298B97F01D17; container ID = "iCloud.com.io.kamaal.PocketSlate">'

# Additional Data

{}

**Comment by kamaal111** [comment]
Done
